version: "3.8"

services:
  postgres:
    container_name: eulodb_container
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eulodb
    volumes:
      - eulodb_pg_data:/bitnami/postgresql

volumes:
  eulodb_pg_data: