import express from "express";
import cookieParser from "cookie-parser";

import { registerUser } from "../routes/register-user.js";
import { verifyUser } from "../routes/verify-user.js";
import { createBrand } from "../routes/create-brand.js";
import { updateBrand } from "../routes/update-brand.js";
import { deleteBrand } from "../routes/delete-brand.js";
import { createProductType } from "../routes/create-product-type.js";
import { updateProductType } from "../routes/update-product-type.js";
import { deleteProductType } from "../routes/delete-product-type.js";
import { createUnitType } from "../routes/create-unit-type.js";
import { updateUnitType } from "../routes/update-unit-type.js";
import { deleteUnitType } from "../routes/delete-unit-type.js";
import { createProduct } from "../routes/create-product.js";
import { getProduct } from "../routes/get-product.js";
import { getProducts } from "../routes/get-products.js";
import { getProductPriceLog } from "../routes/get-product-price-log.js";
import { updateProduct } from "../routes/update-product.js";
import { deleteProduct } from "../routes/delete-product.js";
import { createStorage } from "../routes/create-storage.js";
import { listProductsInStorage } from "../routes/list-products-in-storage.js";
import { deleteStorage } from "../routes/delete-storage.js";
import { addProductsInStorage } from "../routes/add-products-to-storage.js";
import { updateProductQuantityInStorage } from "../routes/update-product-quantity-in-storage.js";
import { removeProductFromStorage } from "../routes/remove-product-from-storage.js";
import { createShoppingList } from "../routes/create-shopping-list.js";
import { getShoppingLists } from "../routes/get-shopping-lists.js";
import { getShoppingListDetails } from "../routes/get-shopping-list-details.js";
import { addProductsInShoppingList } from "../routes/add-products-to-shopping-list.js";
import { printShoppingList } from "../routes/print-shopping-list.js";
import { completeShoppingList } from "../routes/complete-shopping-list.js";
import { autoCreateShoppingList } from "../routes/auto-create-shopping-list.js";
import { removeProductFromShoppingList } from "../routes/remove-product-from-shopping-list.js";
import { deleteShoppingList } from "../routes/delete-shopping-list.js";

const app = express();

app.use(express.json());
app.use(cookieParser());

app.use(autoCreateShoppingList);
app.use(registerUser);
app.use(verifyUser);
app.use(createBrand);
app.use(updateBrand);
app.use(deleteBrand);
app.use(createProductType);
app.use(updateProductType);
app.use(deleteProductType);
app.use(createUnitType);
app.use(updateUnitType);
app.use(deleteUnitType);
app.use(createProduct);
app.use(getProduct);
app.use(getProducts);
app.use(getProductPriceLog);
app.use(updateProduct);
app.use(deleteProduct);
app.use(createStorage);
app.use(listProductsInStorage);
app.use(deleteStorage);
app.use(addProductsInStorage);
app.use(updateProductQuantityInStorage);
app.use(removeProductFromStorage);
app.use(createShoppingList);
app.use(getShoppingLists);
app.use(getShoppingListDetails);
app.use(addProductsInShoppingList);
app.use(printShoppingList);
app.use(completeShoppingList);
app.use(removeProductFromShoppingList);
app.use(deleteShoppingList);

export { app };
